[
	"gmx_tak_army_antiair_g3a3_9k32m_oli",
	"gmx_tak_army_antitank_g3a3_rpg7_oli",
	"gmx_tak_army_antitank_g3a3_pzf84_oli",
	"gmx_tak_army_marksman_g3a3_oli",
	"gmx_tak_army_machinegunner_mg3_oli",
	"gmx_tak_army_machinegunner_pkm_oli",
	"gmx_tak_army_machinegunner_rpk_oli",
	"gmx_tak_army_medic_g3a3_oli",
	"gmx_tak_army_demolition_g3a4_oli"
]