[
	"gm_gc_army_uaz469_spg9_olw",
	"gm_gc_army_uaz469_dshkm_olw",
	"gm_gc_army_btr60pb_olw",
	"gm_gc_army_brdm2rkh_olw",
	"gm_gc_army_btr60pa_dshkm_olw",
	"gm_gc_army_bmp1sp2_olw",
	"gm_gc_army_t55_olw",
	"gm_gc_army_pt76b_olw",
	"gm_gc_army_zsu234v1_olw",
	"gm_gc_airforce_mi2urn_un"
];