[
	"B_D_Heli_Light_01_dynamicLoadout_lxWS",
	"B_Tura_Offroad_armor_armed_lxWS",
	"B_Tura_Offroad_armor_AT_lxWS",
	"B_Tura_Truck_02_aa_lxWS",
	"ION_UAV_02_lxWS",
	"B_Tura_UAV_02_IED_lxWS",
	"B_Tura_ZU23_lxWS",
	"B_Tura_HMG_02_high_lxWS"
];