[
	"O_SFIA_sharpshooter_lxWS",
	"O_SFIA_soldier_at_lxWS",
	"O_SFIA_soldier_aa_lxWS",
	"O_SFIA_HeavyGunner_lxWS",
	"O_SFIA_Soldier_GL_lxWS",
	"O_SFIA_crew_lxWS",
	"O_SFIA_medic_lxWS",
	"O_SFIA_Soldier_AR_lxWS",
	"O_SFIA_exp_lxWS"
]