[
	"I_MBT_03_cannon_F",
	"I_APC_tracked_03_cannon_F",
	"I_APC_Wheeled_03_cannon_F",
	"I_LT_01_AA_F",
	"I_LT_01_AT_F",
	"I_LT_01_cannon_F",
	"I_MRAP_03_gmg_F",
	"I_MRAP_03_hmg_F",
	"I_Heli_light_03_dynamicLoadout_F",
	"I_Truck_02_ammo_F",
	"I_Truck_02_medical_F",
	"I_Truck_02_fuel_F",
	"I_UGV_01_rcws_F"
];