[
	"SPE_ST_PzKpfwIII_J",
	"SPE_FFI_SdKfz250_1",
	"SPE_FFI_OpelBlitz_Ambulance",
	"SPE_FFI_OpelBlitz_Ammo",
	"SPE_FFI_OpelBlitz_Fuel",
	"SPE_FFI_OpelBlitz_Repair",
	"SPE_FW190F8",
	"SPE_FR_M45_Quadmount"
];