[
	"SPE_SdKfz250_1",
	"SPE_PzKpfwIII_J",
	"SPE_PzKpfwIII_L",
	"SPE_PzKpfwIII_M",
	"SPE_PzKpfwIII_N",
	"SPE_PzKpfwIV_G",
	"SPE_PzKpfwVI_H1",
	"SPE_Nashorn",
	"SPE_OpelBlitz_Flak38",
	"SPE_OpelBlitz_Ambulance",
	"SPE_OpelBlitz_Ammo",
	"SPE_OpelBlitz_Fuel",
	"SPE_OpelBlitz_Repair"
];