[
	"B_ION_Heli_Light_02_dynamicLoadout_lxWS",
	"ION_UAV_02_lxWS",
	"B_Tura_UAV_02_IED_lxWS",
	"B_ION_APC_Wheeled_02_hmg_lxWS",
	"B_ION_APC_Wheeled_01_command_lxWS",
	"B_ION_Offroad_armed_lxWS",
	"B_D_APC_Tracked_01_aa_lxWS"
];