[
	"I_C_Soldier_Para_3_F",
	"I_C_Soldier_Bandit_6_F",
	"I_C_Soldier_Para_5_F",
	"I_C_Soldier_Para_8_F",
	"I_C_Soldier_Para_4_F",
	"I_C_Soldier_Bandit_2_F",
	"I_C_Soldier_Bandit_3_F",
	"I_C_Soldier_Para_1_F"
]