[
	"gm_gc_army_sf_antitank_mpikms72_rpg7_80_win",
	"gm_gc_army_sf_machinegunner_lmgrpk_80_win",
	"gm_gc_army_sf_marksman_svd_80_win",
	"gm_gc_army_antitank_mpiak74n_rpg7_80_win",
	"gm_gc_army_medic_mpiak74n_80_win",
	"gm_gc_army_antiair_mpiak74n_9k32m_80_win",
	"gm_gc_army_engineer_mpiaks74n_80_win",
	"gm_gc_army_marksman_svd_80_win",
	"gm_gc_army_antitank_mpiak74n_rpg18_80_win",
	"gm_gc_army_machinegunner_pk_80_win"
]