[
	"O_T_APC_Tracked_02_AA_ghex_F",
	"O_T_APC_Tracked_02_cannon_ghex_F",
	"O_T_APC_Wheeled_02_rcws_v2_ghex_F",
	"O_T_MBT_02_cannon_ghex_F",
	"O_T_MBT_04_cannon_F",
	"O_T_MBT_04_command_F",
	"O_Heli_Attack_02_dynamicLoadout_black_F",
	"O_Heli_Light_02_v2_F",
	"O_T_UGV_01_rcws_ghex_F",
	"O_T_MRAP_02_hmg_ghex_F",
	"O_T_MRAP_02_gmg_ghex_F",
	"O_T_Truck_03_repair_ghex_F",
	"O_T_Truck_03_medical_ghex_F",
	"O_T_Truck_03_fuel_ghex_F",
	"O_T_Truck_03_ammo_ghex_F",
	"O_T_LSV_02_AT_F",
	"O_T_LSV_02_armed_F"
];