[
	"CUP_O_RU_Soldier_HAT_Ratnik_Desert",
	"CUP_O_RU_Soldier_AA_Ratnik_Desert",
	"CUP_O_RU_Recon_LAT_Ratnik_Desert",
	"CUP_O_RU_Soldier_AR_Ratnik_Desert",
	"CUP_O_TK_Soldier_AA",
	"CUP_O_TK_Soldier_AT",
	"CUP_O_TK_Sniper_KSVK",
	"CUP_O_TK_Engineer"
]