[
	"CUP_B_FR_Soldier_AR",
	"CUP_B_USMC_Soldier_Marksman_FROG_WDL",
	"CUP_B_USMC_Soldier_AA",
	"CUP_B_USMC_Soldier_AT_FROG_WDL",
	"CUP_B_USMC_Soldier_HAT",
	"CUP_B_USMC_Medic",
	"CUP_B_USMC_Engineer_FROG_WDL",
	"CUP_B_USMC_Soldier_MG_FROG_WDL"
]