[
	[
		"CUP_B_USMC_FireTeam_AT_FROG_WDL",
		"CUP_B_USMC_FireTeam_FROG_WDL",
		"CUP_B_USMC_FireTeam_MG_FROG_WDL",
		"CUP_B_USMC_FireTeam_Support_FROG_WDL",
		"CUP_B_USMC_HeavyATTeam_FROG_WDL",
		"CUP_B_USMC_InfSquad_FROG_WDL"
	]
];