[
	"SPE_FR_SquadLead",
	"SPE_FR_AT_Soldier",
	"SPE_FR_Autorifleman",
	"SPE_FR_Engineer",
	"SPE_FR_Flamethrower_Operator",
	"SPE_FR_Grenadier",
	"SPE_FR_Medic",
	"SPE_FR_HMGunner",
	"SPE_FR_Rifleman",
	"SPE_FR_Rifleman_Carbine",
	"SPE_FR_Sniper"
];