[
	"I_G_Soldier_AR_F",
	"I_G_medic_F",
	"I_G_Soldier_exp_F",
	"I_G_engineer_F",
	"I_G_Soldier_M_F",
	"I_G_Soldier_GL_F",
	"I_G_Soldier_LAT_F",
	"I_G_Soldier_LAT2_F",
	"I_G_Soldier_lite_F",
	"I_G_Sharpshooter_F"
]