[
	"CUP_O_RU_Soldier_HAT_M_VDV_EMR_V2",
	"CUP_O_RU_Soldier_AA_M_VDV_EMR_V2",
	"CUP_O_RU_Soldier_GL_M_VDV_EMR_V2",
	"CUP_O_RU_Soldier_MG_M_VDV_EMR_V2",
	"CUP_O_RU_Soldier_AT_Ratnik_Autumn",
	"CUP_O_RU_Soldier_Marksman_Ratnik_Autumn",
	"CUP_O_RU_Soldier_Engineer_Ratnik_Autumn",
	"CUP_O_RU_Soldier_AR_Ratnik_Autumn"
]