[
	[
		"East",
		"East",
		"East",
		"East",
		"East"
	],
	[
		"CUP_O_RU",
		"CUP_O_RU",
		"CUP_O_RU",
		"CUP_O_RU",
		"CUP_O_RU"
	], 
	[
		"Infantry_VDV_M", // This aligns with the unit compositions. Since this is index 0 it will use index 0 from the other file.
		"Infantry_Ratnik_Autumn",
		"Infantry_Ratnik_Summer",
		"Infantry_EMR",
		"Infantry_M_EMR"
	]
]